ubot_node:
  ros__parameters:




diff_drive_controller:
  ros__parameters:

    odometry:
      publish_tf: true
      use_imu: true
      frame_id: "odom"
      child_frame_id: "base_footprint"
    
    wheels:
      separation: 0.160
      radius: 0.033
