controller_manager:
  ros__parameters:
    update_rate: 100
    use_sim_time: true

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    diff_drive_base_controller:
      type: diff_drive_controller/DiffDriveController

diff_drive_base_controller:
  ros__parameters:

    publish_rate: 50.0

    left_wheel_names: [wheel_left_joint]
    right_wheel_names: [wheel_right_joint]
    wheel_separation: 0.16
    wheel_radius: 0.033
    wheel_separation_multiplier: 1.0
    left_wheel_radius_multiplier: 1.0
    right_wheel_radius_multiplier: 1.0
    pose_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.03]
    twist_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.03]
    base_frame_id: base_footprint
    use_stamped_vel: false

    cmd_vel_timeout: 0.5 # seconds
    publish_limited_velocity: true
    velocity_rolling_window_size: 10

    # Velocity and acceleration limits for the robot
    linear:
      x:
        has_velocity_limits: true
        max_velocity: 0.2              # m/s
        min_velocity: -0.2             # m/s
        has_acceleration_limits: true
        max_acceleration: 0.6          # m/s^2
    angular:
      z:
        has_velocity_limits: true
        max_velocity: 2.0              # rad/s
        min_velocity: -2.0
        has_acceleration_limits: true
        max_acceleration: 6.0          # rad/s^2
        min_acceleration: -1.0



